{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.TheRedBrain",
    "module": "bundle-api-fabric",
    "version": "1.3.0+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bundle-api-fabric-1.3.0+1.20.1.jar",
          "url": "bundle-api-fabric-1.3.0+1.20.1.jar",
          "size": 87046,
          "sha512": "cf7b64a6676c53a48a9a419c7f6d760bd04c97681b7870075afd7b7123c72e668d6ee2987541ff82c534c30b847bce8bf3bff7dccb11b9c7b5f46413c0720812",
          "sha256": "44f1cec9f23b155a3ac656c34edca95168af932daf2a822570411de63d503f1f",
          "sha1": "f6086445ef73c1ba34352439aca455bfbe13bb41",
          "md5": "9d45809f9547618335bbd1b4d90f8ba6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.5"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.92.12+1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "bundle-api-fabric-1.3.0+1.20.1.jar",
          "url": "bundle-api-fabric-1.3.0+1.20.1.jar",
          "size": 87046,
          "sha512": "cf7b64a6676c53a48a9a419c7f6d760bd04c97681b7870075afd7b7123c72e668d6ee2987541ff82c534c30b847bce8bf3bff7dccb11b9c7b5f46413c0720812",
          "sha256": "44f1cec9f23b155a3ac656c34edca95168af932daf2a822570411de63d503f1f",
          "sha1": "f6086445ef73c1ba34352439aca455bfbe13bb41",
          "md5": "9d45809f9547618335bbd1b4d90f8ba6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bundle-api-fabric-1.3.0+1.20.1-sources.jar",
          "url": "bundle-api-fabric-1.3.0+1.20.1-sources.jar",
          "size": 2377,
          "sha512": "0ade81ded984af443011bf58a1818efba106e873a8bfb5c47fe678a87648bdcb76919b1e64ab5fd18a8b005b9adfae0a5eacff18808bbc0c7b0fa1124b52f09e",
          "sha256": "0998d333d22cf635dec375826de73a35e2d502eff6831c591095a861fe979104",
          "sha1": "0b47a1f7d58abc082a286d5e778a7a805e5bdaec",
          "md5": "9a0bcc0bc6f14a77b341b93eb36b66f9"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bundle-api-fabric-1.3.0+1.20.1-dev-shadow.jar",
          "url": "bundle-api-fabric-1.3.0+1.20.1-dev-shadow.jar",
          "size": 86929,
          "sha512": "cb7a8c40b21ea35441527475e374df1849f3abfd3c6d4ac7f34f096188a38e0ccbf1ee55c82f3fd29d116c26cee23f10f5099e8c4b1f596336bfe9a4f7e9204d",
          "sha256": "f0ea6238508ca494fdd14c30128276db57ca652908b42caa14bc4f511250cfe0",
          "sha1": "26b517368b6efb33ca2d12a9dfba991b2b77ea96",
          "md5": "28f2fac4292b6977c30b4211a5d61fc4"
        }
      ]
    }
  ]
}
