{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.TheRedBrain",
    "module": "bundle-api-forge",
    "version": "1.3.0+1.20.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bundle-api-forge-1.3.0+1.20.1.jar",
          "url": "bundle-api-forge-1.3.0+1.20.1.jar",
          "size": 87439,
          "sha512": "5faa8e37c4f32cb9ed6a5b3b34044735460bd385cd29bedec1aad192125f488d494598662e58d8f564e7bfb7ef902e8b90206d45f290b80b734308618f7ce5dc",
          "sha256": "090e66ee05c49f4d30583b06c2988e51dc43d3676dd5ab7da44aec94f4a79634",
          "sha1": "1dbdbe40c9304983a6ac16da9b1f0b968b2490d7",
          "md5": "345506dffd922507d032f5b1f0ebbc3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bundle-api-forge-1.3.0+1.20.1.jar",
          "url": "bundle-api-forge-1.3.0+1.20.1.jar",
          "size": 87439,
          "sha512": "5faa8e37c4f32cb9ed6a5b3b34044735460bd385cd29bedec1aad192125f488d494598662e58d8f564e7bfb7ef902e8b90206d45f290b80b734308618f7ce5dc",
          "sha256": "090e66ee05c49f4d30583b06c2988e51dc43d3676dd5ab7da44aec94f4a79634",
          "sha1": "1dbdbe40c9304983a6ac16da9b1f0b968b2490d7",
          "md5": "345506dffd922507d032f5b1f0ebbc3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bundle-api-forge-1.3.0+1.20.1-sources.jar",
          "url": "bundle-api-forge-1.3.0+1.20.1-sources.jar",
          "size": 2156,
          "sha512": "b7a777cc8a7c710a3093bd69423a0cf1c6fec518b017fe02559fee6859ab7b2af515b9d7a607c541123fa2bf436dae63b4172d70440e7e5d7f2621b9611cb607",
          "sha256": "cbf1a295c77fc143fc1d9c36cc40c034c54fb1d47798bf2657b490508e7bd2c8",
          "sha1": "91df79bc18c75beb4ee537628816f6c22fde4065",
          "md5": "e7f66725d7dec0de3576602176d3ca59"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bundle-api-forge-1.3.0+1.20.1-dev-shadow.jar",
          "url": "bundle-api-forge-1.3.0+1.20.1-dev-shadow.jar",
          "size": 87135,
          "sha512": "1f174215c9a16d8f66047b6a8f4bad7cdad3d5c03a1e1591266a59e5b33f5dde342302756252668945dc1f9afa8fbf65dee477015f48eae6dd1b8d7facd8b59c",
          "sha256": "8d52bc847a923c7a20fd669994ef4c496ed7658fe972bb1009487a4c1f959c26",
          "sha1": "4cd02dfb12b0524c6f5a7b7299af1679f0dc31ad",
          "md5": "4071849370cab58939c4566846e3900d"
        }
      ]
    }
  ]
}
