modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ZsoltMolnarrr/SpellEngine/issues"
license = "GPL-3.0"

[[mods]]
modId = "spell_engine"
version = "${version}"
displayName = "Spell Engine"
authors = "Daedelus"
description = '''
Data driven magic library.
'''
logoFile = "icon.png"

[[dependencies.spell_engine]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_engine]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_compat_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_engine]]
modId = "forgified_fabric_api"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_engine]]
modId = "cloth_config"
type = "required"
versionRange = "[${cloth_config_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_engine]]
modId = "playeranimator"
type = "required"
versionRange = "[1.9.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_engine]]
modId = "spell_power"
type = "required"
versionRange = "[${spell_power_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_engine]]
modId = "accessories"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "spell_engine.mixins.json"

[[mixins]]
config = "spell_engine-neoforge.mixins.json"
