modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ZsoltMolnarrr/SpellEngine/issues"
license = "GPL-3.0"

[[mods]]
modId = "spell_engine"
version = "${version}"
displayName = "Spell Engine"
authors = "Daedelus"
description = '''
Data driven magic library.
'''
iconFile = "icon.png"

[[dependencies.spell_engine]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_engine]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_min_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_engine]]
modId = "cloth_config"
type = "required"
versionRange = "[${cloth_config_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_engine]]
modId = "player_animation_library"
type = "required"
versionRange = "[1.2.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_engine]]
modId = "spell_power"
type = "required"
versionRange = "[${spell_power_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spell_engine]]
modId = "curios"
type = "optional"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "spell_engine.mixins.json"

[[mixins]]
config = "spell_engine-neoforge.mixins.json"
